database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: 'jdbc:mysql://0.0.0.0:8801/test?createDatabaseIfNotExist=true&characterEncoding=UTF-8&forceConnectionTimeZoneToSession=true&preserveInstants=true&connectionTimeZone=UTC'
  user: root
  password: venturegain

server:
  adminContextPath: /admin
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081